### PR TITLE
split modules into partials

### PR DESCRIPTION
**Pull request by marcobiedermann**
I slit all modules into it's own partial.
The file structure will look like this:

```
gutenberg.scss
_gutenberg-config.scss
helpers
  _alignment.scss
  _grid.scss
layout
  _aside.scss
  _base.scss
  _footer.scss
  _header.scss
  _main.scss
  _section.scss
mixins
  _font-size.scss
  _line-height.scss
  _margin.scss
  _padding.scss
 modules
  _anchor.scss
  _article.scss
  _audio.scss
  _canvas.scss
  _code.scss
  _details.scss
  _figure.scss
  _form.scss
  _headline.scss
  _horizontal-rule.scss
  _image.scss
  _list.scss
  _navigation.scss
  _progress.scss
  _quote.scss
  _table.scss
  _template.scss
  _text.scss
  _video.scss
```

### CODE REVIEW

**Comment by matejlatin** [comment]
Wow, seems like a lot of work :) @marcobiedermann is this a more conventional way of structuring projects like this?

**Comment by marcobiedermann** [comment]
@matejlatin This is not an official structure / architecture.
In my opinion I does make sense splitting things up like that because everything lives in it's own file.
The big advantage of this is that users can easily comment out the files, which they do not need.
For example, if you do not use and `audio` or `video` files in you project, you only need to remove / comment out two lines of code in `gutenberg.scss`.
This makes testing and expanding really easy.

**Comment by matejlatin** [comment]
@marcobiedermann cool, will take a closer look later this week and merge it. I'll also have to update the documentation and release for this update.

**Comment by marcobiedermann** [comment]
@matejlatin Hey Matej, any updates from your side?

**Comment by matejlatin** [comment]
Hey @marcobiedermann still working on it. Should be up in a day or two.

**Pull request merged**
