### PR TITLE
Add TravisCI setup and test script #27

### PR DESCRIPTION
**Pull request by tricinel**
At the moment, the test will fail, because we still have unresolved stylelint errors. We also need to sign up for a free TravisCI account here: https://travis-ci.org/

### CODE REVIEW

**Comment by tricinel** [comment]
Looks like you did it already, but there's some stylelint install error. Looking into it now.

**Comment by matejlatin** [comment]
@tricinel cool, should I merge this?

**Comment by tricinel** [comment]
OK, we have travis ci running correctly now. It still fails because of the stylelint errors. If it's ok with you, then I can go through the list of warnings and errors and happily fix them.

Travis is working alright though...

**Comment by matejlatin** [comment]
Cool, yeah if you have time, that would be great... :) Should I merge now or wait for those fixes?

**Comment by tricinel** [comment]
Well, they're independent. It'd be good to see the build succeed when I'm done with fixes though. So maybe merge?

**Comment by matejlatin** [comment]
Done 👍

**Comment by matejlatin** [comment]
Thanks for contributing btw ;)

**Comment by tricinel** [comment]
You're more than welcome! I'm sorry I don't get to do it much more often...

Thank you!

**Pull request merged**
